# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "zvlex.dev"
description: > # this means to ignore newlines until "email:"
   A Jekyll theme - Medium inspired

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/4821468.png"
float_logo: true # true, false (default)

# blog cover
# cover: "/assets/images/1280x800-rubymine.png"

name: 'Alexander Zutikov'
author: 'Alexander Zutikov'
author_image: "/assets/images/4821468.png"

paginate:	2

url: "https://zvlex.dev" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@zvlex'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/zvlex
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/zvlex
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
